name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deployment Placeholder
        run: |
          echo "Terraform deployment will be added in Sprint 2."